### ISSUE TITLE
Improved behaviour of applyverbs.py

### ISSUE THREAD

**Issue by woody6402** [ryanprescott/realtek-verb-tools#3]
in a recent sound kernel analyzes if was helpfull to add comments and empty lines to the verb file.
See attached code with very small changes applied by another contributor,
[applyverbs.py.txt](https://github.com/ryanprescott/realtek-verb-tools/files/6719886/applyverbs.py.txt)

**Comment by ryanprescott** [comment]
Duplicate of Improved behaviour of applyverbs.py #4
