### ISSUE TITLE
using a dual boot instead of VM ?

### ISSUE THREAD

**Issue by bananasmoothii** [ryanprescott/realtek-verb-tools#5]
Hello, I have windows 10 dual-booted, and sound works over there, can I use it instead of installing a VM for "sniffing verbs" as described in the wiki ? Kinda lazy to download a new iso with my grandma connectivity...

**Comment by ryanprescott** [comment]
I'm not sure that this would work because you wouldn't be able to access
the underlying verbs being passed between the driver and the hardware which
is critical to this process.
